### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by PiNotEqual3** [magendooro/magento-fulltext-reindex#1]
Can you give an example how to use it?

I installed it and run `php indexer.php --reindex catalogsearch_fulltext` but no temporary table is used.

**Comment by florinel-chis** [comment]
Hello,

1) Did you clear the cache after installing the module
2) Can you see the module listed in: `System -> Configuration -> Advanced`
3) What settings do you use for Catalog Search: `System -> Configuration -> Catalog -> Catalog Search`
Would be also useful to specify your Magento version

**Comment by carco** [comment]
Also, can you put this code into fttest.php file (into the magento root), then run `php fttest.php` and post the result:

```
<?php

ini_set('display_errors',1);
error_reporting(E_ALL|E_STRICT);

require 'app/Mage.php';
Mage::setIsDeveloperMode(true);

umask(0);
Mage::app();


$model  = Mage::getModel('catalogsearch/indexer_fulltext');
$engine =  Mage::helper('catalogsearch')->getEngine();

echo 'Model Used: ',$model?get_class($model):'-',"\n";
echo 'Engine Used: ',$engine?get_class($engine):'-',"\n";
```

Expected result:

```
php fttest.php 
Model Used: Magendoo_Fulltext_Model_Indexer_Fulltext
Engine Used: Mage_CatalogSearch_Model_Resource_Fulltext_Engine
```

If the module runs OK, after fulltext reindex, you should be able to see a table named `catalogsearch_fulltext_prev` and a log file `fulltext-reindex.log` (into var/log/ directory).

**Comment by PiNotEqual3** [comment]
Ok, I guess I just forgott to clear the cache. `get_class( Mage::getModel('catalogsearch/indexer_fulltext') )` shows the correct module now. Thanks!
