### ISSUE TITLE
combine witch sphinxsearch

### ISSUE THREAD

**Issue by Kamik** [magendooro/magento-fulltext-reindex#3]
how to combine with this extension https://github.com/fheyer/sphinxsearch ?

**Comment by florinel-chis** [comment]
why would you want to do that? and what do you mean by "combine"?

**Comment by Kamik** [comment]
I mean that both extensions are not working together. Table sphinx_catalogsearch_fulltext remains empty. Both extensions rewrite class Mage_CatalogSearch_Model_Resource_Fulltext.

**Comment by carco** [comment]
Why you want to use both? This small extension fix a problem with magento default indexer, you don't need if you use another indexer (like sphinx). 

Also, this extension does not rewrite Mage_CatalogSearch_Model_Resource_Fulltext, but Mage_CatalogSearch_Model_Indexer_Fulltext.

If you insist to use both, you need to change Magendoo_Fulltext_Model_Indexer_Fulltext class adding something like:

`||  Mage::getStoreConfigFlag('sphinxsearch/active/indexer')`

on line 21 ( https://github.com/magendooro/magento-fulltext-reindex/blob/master/app/code/local/Magendoo/Fulltext/Model/Indexer/Fulltext.php#L21 )

**Comment by Kamik** [comment]
Thank you. 
Is it possible to realize the creation of indexes in a temporary table and copy it to sphinx_catalogsearch_fulltext. In general, improve creation speed of sphinxsearch index table?

**Comment by theycallmepepper** [comment]
@florinel-chis https://github.com/jeroenvermeulen/magento-solarium/issues/42  That should give you a heads up as to why you may want to use this extension alongside something like Solr or sphinx.  Occasionally there are issues trying to perform a search using those extensions while magento is trying to reindex `catalogsearch_fulltext`.
