### ISSUE TITLE
How to install/run?

### ISSUE THREAD

**Issue by SupraMario** [magendooro/magento-fulltext-reindex#4]
How do we install and run this code? There's no mention of how to use it.

**Comment by florinel-chis** [comment]
- you install the module
- you run the fulltext search reindex

If any of the steps above don't make sense, please find a Magento developer.

**Comment by SupraMario** [comment]
Our magento developer was the one asking the query, that is why I posted. Perhaps this doenst work with magento 1.8

**Comment by CajuCLC** [comment]
It was already answered.
You just install the module.
Then run the reindex from the admin.

The module works great.
That's all.

**Comment by SupraMario** [comment]
Anyone who finds this and it doesn't work via admin -

php indexer.php --reindexall
or
php indexer.php -reindex catalogsearch_fulltext
